// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	models "github.com/Shaheen-AlQaraghuli/wallet-go/internal/app/models"

	mock "github.com/stretchr/testify/mock"

	pagination "github.com/Shaheen-AlQaraghuli/wallet-go/internal/util/pagination"
)

// MockWalletDB is an autogenerated mock type for the walletDB type
type MockWalletDB struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, wallet
func (_m *MockWalletDB) Create(ctx context.Context, wallet models.Wallet) (models.Wallet, error) {
	ret := _m.Called(ctx, wallet)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 models.Wallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Wallet) (models.Wallet, error)); ok {
		return rf(ctx, wallet)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.Wallet) models.Wallet); ok {
		r0 = rf(ctx, wallet)
	} else {
		r0 = ret.Get(0).(models.Wallet)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.Wallet) error); ok {
		r1 = rf(ctx, wallet)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockWalletDB) GetByID(ctx context.Context, id string) (models.Wallet, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 models.Wallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (models.Wallet, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) models.Wallet); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(models.Wallet)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, query
func (_m *MockWalletDB) List(ctx context.Context, query models.QueryWallets) ([]models.Wallet, *pagination.Pagination, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []models.Wallet
	var r1 *pagination.Pagination
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, models.QueryWallets) ([]models.Wallet, *pagination.Pagination, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.QueryWallets) []models.Wallet); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Wallet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.QueryWallets) *pagination.Pagination); ok {
		r1 = rf(ctx, query)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*pagination.Pagination)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, models.QueryWallets) error); ok {
		r2 = rf(ctx, query)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Update provides a mock function with given fields: ctx, wallet
func (_m *MockWalletDB) Update(ctx context.Context, wallet models.Wallet) (models.Wallet, error) {
	ret := _m.Called(ctx, wallet)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 models.Wallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Wallet) (models.Wallet, error)); ok {
		return rf(ctx, wallet)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.Wallet) models.Wallet); ok {
		r0 = rf(ctx, wallet)
	} else {
		r0 = ret.Get(0).(models.Wallet)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.Wallet) error); ok {
		r1 = rf(ctx, wallet)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockWalletDB creates a new instance of MockWalletDB. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWalletDB(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWalletDB {
	mock := &MockWalletDB{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
