version: "3.9"

services:
  postgres:
    image: postgres:15.4-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "example"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "wallet"
  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
